### ISSUE TITLE
crash in rebased branch

### ISSUE THREAD

**Issue by dabokun** [aflak-vis/aflak#68]
In https://github.com/aflak-vis/aflak/commit/6a6b0a07f459580f3d4fc3157b88a0c092976249, aflak crashes when it starts up.
Here's the stack trace. It seems the problem occurs in backend (unconfident). I don't know why this problem wasn't reproduced in other rebased branches...

```patch
dabokun@debian:~/aflak-vis/dabokun/aflak/src$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/aflak`
thread 'main' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55a7df2a37f4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55a7df2a37f4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55a7df2a37f4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55a7df2a37f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55a7df2c74ec - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55a7df2a09a7 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55a7df2a5d45 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55a7df2a5d45 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55a7df2a5d45 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55a7df2a5a36 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55a7df2a6445 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55a7df2a5fe2 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55a7df2a5ed6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55a7df2c2e1a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x55a7df2c2f17 - core::result::unwrap_failed::ha8b77e6004f0ba38
                               at src/libcore/result.rs:1165
  15:     0x55a7de97a48b - core::result::Result<T,E>::expect::h177311a03f548076
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:960
  16:     0x55a7de97007d - core::cell::RefCell<T>::borrow_mut::heb7d6518a7ecea54
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/cell.rs:869
  17:     0x55a7de959488 - <glium::backend::glutin::GlutinBackend as glium::backend::Backend>::make_current::h9fb037b36b1d2081
                               at /home/dabokun/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.25.1/src/backend/glutin/mod.rs:285
  18:     0x55a7dec6dda0 - <glium::context::Context as glium::ContextExt>::make_current::h5b7c79d67ad160e6
                               at /home/dabokun/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.25.1/src/context/mod.rs:644
  19:     0x55a7dec7a978 - glium::ops::clear::clear::hd89825e7035c4fc2
                               at /home/dabokun/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.25.1/src/ops/clear.rs:20
  20:     0x55a7de6af905 - <glium::Frame as glium::Surface>::clear::h78384d83101f476c
                               at /home/dabokun/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.25.1/src/lib.rs:1153
  21:     0x55a7de6af460 - glium::Surface::clear_color::h8e6265b375ac9d99
                               at /home/dabokun/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.25.1/src/lib.rs:689
  22:     0x55a7de6b69ec - aflak_imgui_glium_support::run::hf379b66b70284dbc
                               at /home/dabokun/aflak-vis/dabokun/aflak/src/imgui_glium_support/src/lib.rs:172
  23:     0x55a7de6de3c9 - aflak::main::hf8a0e5a1501dcfdf
                               at src/main.rs:71
  24:     0x55a7de51f4c8 - std::rt::lang_start::{{closure}}::h772549951f730769
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  25:     0x55a7df2a5e73 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  26:     0x55a7df2a5e73 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  27:     0x55a7df2aa4aa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  28:     0x55a7df2a69fd - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  29:     0x55a7df2a69fd - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  30:     0x55a7df2a69fd - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  31:     0x55a7de51f499 - std::rt::lang_start::h4784d144f935dca5
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  32:     0x55a7de6df22a - main
  33:     0x7f4dd56ce2e1 - __libc_start_main
  34:     0x55a7de51f1aa - _start
  35:                0x0 - <unknown>
thread 'main' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:1165:5
stack backtrace:
   0:     0x55a7df2a37f4 - backtrace::backtrace::libunwind::trace::hda41dbcdfba36aa0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1:     0x55a7df2a37f4 - backtrace::backtrace::trace_unsynchronized::h1a8d6e1f8cb3f5d4
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2:     0x55a7df2a37f4 - std::sys_common::backtrace::_print_fmt::h610c4127487e10da
                               at src/libstd/sys_common/backtrace.rs:76
   3:     0x55a7df2a37f4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h0722dc552e01bd1d
                               at src/libstd/sys_common/backtrace.rs:60
   4:     0x55a7df2c74ec - core::fmt::write::h01edf6dd68a42c9c
                               at src/libcore/fmt/mod.rs:1030
   5:     0x55a7df2a09a7 - std::io::Write::write_fmt::hf15985f193f03c04
                               at src/libstd/io/mod.rs:1412
   6:     0x55a7df2a5d45 - std::sys_common::backtrace::_print::hd8d5d08a1795e743
                               at src/libstd/sys_common/backtrace.rs:64
   7:     0x55a7df2a5d45 - std::sys_common::backtrace::print::hf89a79e3921a2366
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55a7df2a5d45 - std::panicking::default_hook::{{closure}}::h3a8f42beb3bb8ae3
                               at src/libstd/panicking.rs:196
   9:     0x55a7df2a5a36 - std::panicking::default_hook::h8f803b0bc31a5c37
                               at src/libstd/panicking.rs:210
  10:     0x55a7df2a6445 - std::panicking::rust_panic_with_hook::h825f041245da8739
                               at src/libstd/panicking.rs:473
  11:     0x55a7df2a5fe2 - std::panicking::continue_panic_fmt::hbe0378e33481e81b
                               at src/libstd/panicking.rs:380
  12:     0x55a7df2a5ed6 - rust_begin_unwind
                               at src/libstd/panicking.rs:307
  13:     0x55a7df2c2e1a - core::panicking::panic_fmt::h527855ce0bc891f6
                               at src/libcore/panicking.rs:85
  14:     0x55a7df2c2f17 - core::result::unwrap_failed::ha8b77e6004f0ba38
                               at src/libcore/result.rs:1165
  15:     0x55a7de97a48b - core::result::Result<T,E>::expect::h177311a03f548076
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:960
  16:     0x55a7de97007d - core::cell::RefCell<T>::borrow_mut::heb7d6518a7ecea54
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/cell.rs:869
  17:     0x55a7de959488 - <glium::backend::glutin::GlutinBackend as glium::backend::Backend>::make_current::h9fb037b36b1d2081
                               at /home/dabokun/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.25.1/src/backend/glutin/mod.rs:285
  18:     0x55a7dec6dda0 - <glium::context::Context as glium::ContextExt>::make_current::h5b7c79d67ad160e6
                               at /home/dabokun/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.25.1/src/context/mod.rs:644
  19:     0x55a7dec54673 - <glium::program::raw::RawProgram as core::ops::drop::Drop>::drop::h2f8b820e16566741
                               at /home/dabokun/.cargo/registry/src/github.com-1ecc6299db9ec823/glium-0.25.1/src/program/raw.rs:674
  20:     0x55a7de621305 - core::ptr::real_drop_in_place::h62794d15fa9e03e1
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  21:     0x55a7de61dd41 - core::ptr::real_drop_in_place::h2a656288a58cb732
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  22:     0x55a7de6266e8 - core::ptr::real_drop_in_place::hb9e671675a26f283
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/ptr/mod.rs:175
  23:     0x55a7de6b6566 - aflak_imgui_glium_support::run::hf379b66b70284dbc
                               at /home/dabokun/aflak-vis/dabokun/aflak/src/imgui_glium_support/src/lib.rs:189
  24:     0x55a7de6de3c9 - aflak::main::hf8a0e5a1501dcfdf
                               at src/main.rs:71
  25:     0x55a7de51f4c8 - std::rt::lang_start::{{closure}}::h772549951f730769
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  26:     0x55a7df2a5e73 - std::rt::lang_start_internal::{{closure}}::ha04574f12d97cbe2
                               at src/libstd/rt.rs:49
  27:     0x55a7df2a5e73 - std::panicking::try::do_call::h7c2a8488f72db90c
                               at src/libstd/panicking.rs:292
  28:     0x55a7df2aa4aa - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  29:     0x55a7df2a69fd - std::panicking::try::hc3a9b5da4250385d
                               at src/libstd/panicking.rs:271
  30:     0x55a7df2a69fd - std::panic::catch_unwind::hf27600bf8c37809a
                               at src/libstd/panic.rs:394
  31:     0x55a7df2a69fd - std::rt::lang_start_internal::h409d4f2fe51133b0
                               at src/libstd/rt.rs:48
  32:     0x55a7de51f499 - std::rt::lang_start::h4784d144f935dca5
                               at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  33:     0x55a7de6df22a - main
  34:     0x7f4dd56ce2e1 - __libc_start_main
  35:     0x55a7de51f1aa - _start
  36:                0x0 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction
```

**Comment by malikolivier** [comment]
Sorry, I probably did something wrong during the rebase. I will investigate.
